from typing import Any


BORROWERS: list[dict[str, Any]] = [
    {
        "id": 1,
        "name": "Northbridge Components Ltd",
        "sector": "Manufacturing",
        "country": "United Kingdom",
        "internal_risk_band": "moderate",
        "revenue_m": 520.0,
        "ebitda_m": 82.0,
        "total_debt_m": 245.0,
        "cash_m": 38.0,
        "interest_expense_m": 24.0,
        "last_financials_date": "2026-08-31",
        "watchlist": False,
    },
    {
        "id": 2,
        "name": "Meridian Logistics Group",
        "sector": "Transport and Logistics",
        "country": "United Kingdom",
        "internal_risk_band": "elevated",
        "revenue_m": 760.0,
        "ebitda_m": 96.0,
        "total_debt_m": 365.0,
        "cash_m": 28.0,
        "interest_expense_m": 31.0,
        "last_financials_date": "2026-07-31",
        "watchlist": True,
    },
    {
        "id": 3,
        "name": "Asteron Retail Group",
        "sector": "Retail",
        "country": "United Kingdom",
        "internal_risk_band": "high",
        "revenue_m": 1180.0,
        "ebitda_m": 108.0,
        "total_debt_m": 470.0,
        "cash_m": 42.0,
        "interest_expense_m": 39.0,
        "last_financials_date": "2026-03-31",
        "watchlist": True,
    },
    {
        "id": 4,
        "name": "Helios Renewables plc",
        "sector": "Renewable Energy",
        "country": "United Kingdom",
        "internal_risk_band": "low",
        "revenue_m": 640.0,
        "ebitda_m": 156.0,
        "total_debt_m": 310.0,
        "cash_m": 74.0,
        "interest_expense_m": 22.0,
        "last_financials_date": "2026-08-31",
        "watchlist": False,
    },
    {
        "id": 5,
        "name": "Redwood Healthcare Holdings",
        "sector": "Healthcare",
        "country": "United Kingdom",
        "internal_risk_band": "moderate",
        "revenue_m": 430.0,
        "ebitda_m": 71.0,
        "total_debt_m": 205.0,
        "cash_m": 31.0,
        "interest_expense_m": 18.0,
        "last_financials_date": "2026-06-30",
        "watchlist": False,
    },
    {
        "id": 6,
        "name": "Orion Business Services",
        "sector": "Business Services",
        "country": "United Kingdom",
        "internal_risk_band": "elevated",
        "revenue_m": 295.0,
        "ebitda_m": 47.0,
        "total_debt_m": 181.0,
        "cash_m": 19.0,
        "interest_expense_m": 17.0,
        "last_financials_date": "2026-05-31",
        "watchlist": True,
    },
]


FACILITIES: list[dict[str, Any]] = [
    {
        "id": 1,
        "borrower_id": 1,
        "facility_type": "revolving_credit",
        "currency": "GBP",
        "committed_amount_m": 120.0,
        "drawn_amount_m": 85.0,
        "margin_bps": 225,
        "maturity_date": "2029-06-30",
        "secured": False,
    },
    {
        "id": 2,
        "borrower_id": 2,
        "facility_type": "term_loan",
        "currency": "GBP",
        "committed_amount_m": 250.0,
        "drawn_amount_m": 250.0,
        "margin_bps": 310,
        "maturity_date": "2028-12-31",
        "secured": True,
    },
    {
        "id": 3,
        "borrower_id": 3,
        "facility_type": "revolving_credit",
        "currency": "GBP",
        "committed_amount_m": 180.0,
        "drawn_amount_m": 145.0,
        "margin_bps": 375,
        "maturity_date": "2028-03-31",
        "secured": True,
    },
    {
        "id": 4,
        "borrower_id": 4,
        "facility_type": "term_loan",
        "currency": "GBP",
        "committed_amount_m": 220.0,
        "drawn_amount_m": 210.0,
        "margin_bps": 180,
        "maturity_date": "2031-09-30",
        "secured": False,
    },
    {
        "id": 5,
        "borrower_id": 5,
        "facility_type": "revolving_credit",
        "currency": "GBP",
        "committed_amount_m": 100.0,
        "drawn_amount_m": 62.0,
        "margin_bps": 240,
        "maturity_date": "2029-01-31",
        "secured": False,
    },
    {
        "id": 6,
        "borrower_id": 6,
        "facility_type": "acquisition_facility",
        "currency": "GBP",
        "committed_amount_m": 150.0,
        "drawn_amount_m": 138.0,
        "margin_bps": 340,
        "maturity_date": "2028-06-30",
        "secured": True,
    },
]


COVENANTS: list[dict[str, Any]] = [
    {
        "id": 1,
        "facility_id": 1,
        "metric": "net_leverage",
        "threshold": 4.0,
        "comparison": "maximum",
        "testing_frequency": "quarterly",
        "last_test_date": "2026-06-30",
    },
    {
        "id": 2,
        "facility_id": 1,
        "metric": "interest_cover",
        "threshold": 2.5,
        "comparison": "minimum",
        "testing_frequency": "quarterly",
        "last_test_date": "2026-06-30",
    },
    {
        "id": 3,
        "facility_id": 2,
        "metric": "net_leverage",
        "threshold": 3.75,
        "comparison": "maximum",
        "testing_frequency": "quarterly",
        "last_test_date": "2026-06-30",
    },
    {
        "id": 4,
        "facility_id": 2,
        "metric": "interest_cover",
        "threshold": 2.75,
        "comparison": "minimum",
        "testing_frequency": "quarterly",
        "last_test_date": "2026-06-30",
    },
    {
        "id": 5,
        "facility_id": 3,
        "metric": "net_leverage",
        "threshold": 4.25,
        "comparison": "maximum",
        "testing_frequency": "quarterly",
        "last_test_date": "2026-06-30",
    },
    {
        "id": 6,
        "facility_id": 3,
        "metric": "interest_cover",
        "threshold": 2.5,
        "comparison": "minimum",
        "testing_frequency": "quarterly",
        "last_test_date": "2026-06-30",
    },
    {
        "id": 7,
        "facility_id": 4,
        "metric": "net_leverage",
        "threshold": 3.0,
        "comparison": "maximum",
        "testing_frequency": "semi_annual",
        "last_test_date": "2026-06-30",
    },
    {
        "id": 8,
        "facility_id": 5,
        "metric": "net_leverage",
        "threshold": 3.5,
        "comparison": "maximum",
        "testing_frequency": "quarterly",
        "last_test_date": "2026-06-30",
    },
    {
        "id": 9,
        "facility_id": 5,
        "metric": "interest_cover",
        "threshold": 2.5,
        "comparison": "minimum",
        "testing_frequency": "quarterly",
        "last_test_date": "2026-06-30",
    },
    {
        "id": 10,
        "facility_id": 6,
        "metric": "net_leverage",
        "threshold": 4.0,
        "comparison": "maximum",
        "testing_frequency": "quarterly",
        "last_test_date": "2026-06-30",
    },
    {
        "id": 11,
        "facility_id": 6,
        "metric": "interest_cover",
        "threshold": 2.25,
        "comparison": "minimum",
        "testing_frequency": "quarterly",
        "last_test_date": "2026-06-30",
    },
]